name: CD
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type (one of): patch, minor, major, prepatch, preminor, premajor'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: NPM configuration
        run: echo "//registry.npmjs.org/:_authToken $NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepack

      - name: Publish package
        run: yarn release --ci --increment ${{ github.event.inputs.release-type }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
